services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python backend.py
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
